name: Snake Game

on:
  # Executa a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite executar manualmente na aba Actions
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do seu repositório para a action poder acessá-lo
      - uses: actions/checkout@v4

      # Gera os arquivos da cobrinha (SVG e GIF)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # Seu nome de usuário do GitHub
          github_user_name: GabrielBorges0210
          # Define os nomes dos arquivos de saída
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=purple

      # Commita e envia os arquivos gerados de volta para a sua branch principal
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"
          file_pattern: "dist/*" # Commita apenas as alterações na pasta dist
